source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/RebelCreators/BravoSpecs.git'

inhibit_all_warnings!

target 'BravoTests' do
  use_frameworks!

  pod 'Bravo', :path => '../'
  pod 'HHSDK', :path => '../'
end

target 'BravoTestsUnitTests' do
    use_frameworks!
    
    pod 'Bravo', :path => '../'
    pod 'HHSDK', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
